FROM golang:1.26-bookworm AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/migrate ./cmd/migrate/main.go

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/migrate .
COPY --from=builder /app/internal/database/migration ./internal/database/migration

CMD ["./migrate", "up"]